# Generated by Django 4.1.1 on 2022-10-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='anotacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=50)),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('CorAnotacaoUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CorAnotacaoUser', to='noteon4.anotacoes')),
                ('SubtituloAnotacaoUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubtituloAnotacaoUser', to='noteon4.anotacoes')),
                ('TextoAnotacaoUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TextoAnotacaoUser', to='noteon4.anotacoes')),
                ('TituloAnotacaoUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TituloAnotacaoUser', to='noteon4.anotacoes')),
            ],
        ),
    ]
