# Generated by Django 4.1.1 on 2022-10-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteon4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='sobrenome',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
