# Generated by Django 4.1.1 on 2022-10-04 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noteon4', '0003_remove_usuarios_coranotacaouser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='anotacoes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='noteon4.anotacoes'),
            preserve_default=False,
        ),
    ]
