# Generated by Django 4.1.1 on 2022-10-04 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noteon4', '0004_usuarios_anotacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='anotacoes',
        ),
        migrations.AddField(
            model_name='anotacoes',
            name='usuarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='noteon4.usuarios'),
            preserve_default=False,
        ),
    ]
